### ISSUE TITLE
Tasks Required for Promotion to Kokkos core 

### ISSUE THREAD

**Issue by jeffmiles63** [kokkos/simd-math#21]
Below is a list of features and additions required to prepared simd-math for Kokkos promotion:

- [ ] CMake build elements
- [ ] Unit test suite which is build friendly
- [ ] Testing scripts to validate on hardware/compiler matrix
- [ ] features previously outlined in #1 
- [x] missing operators listed in #4 
- [ ]  #15 
- [x]  #16
- [ ] features for core integration ( #22 )

edited by @ibaned to add checkboxes

**Comment by jeffmiles63** [comment]
@ibaned I agree #22 will addressed in a separate PR in the Kokkos core. i thought the discussion should originate here.

**Comment by jeffmiles63** [comment]
@tasmith4 if you have appropriate test fixtures we can start with that would be a great help.

**Comment by tasmith4** [comment]
@jeffmiles63 I was going to point you to Trilinos but I see we haven't gotten the latest updates there yet.  I will submit another snapshot PR by tonight unless @alanw0 beats me to it.

**Comment by alanw0** [comment]
@tasmith4 I'm not going to beat you to it. I'm up to my eye-balls trying to debug the vortex stuff that empire is up against...

**Comment by tasmith4** [comment]
@jeffmiles63 check out `packages/stk/stk_unit_tests/stk_simd` in Trilinos/develop.  There's a couple things that might need to be tweaked or extended to test the whole range of functionality (our new unit tests are not yet complete, we have a story on this sprint to wrap that up), but hopefully this is a helpful starting point.  Let me know if you have questions.

**Comment by jeffmiles63** [comment]
@tasmith4 thanks for the update.

**Comment by alanw0** [comment]
@jeffmiles63 Unfortunately I have a pull-request in progress to revert that code that @tasmith4 refers to above...
It has a problem with cmake/install which has broken nalu and nalu-wind. We'll have it fixed and back in shortly though.
